version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  web:
    image: webapp:latest
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DEBUG=${DJANGO_DEBUG}
      - SECRET_KEY=${DJANGO_SECRET_KEY}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    depends_on:
      - postgres

volumes:
  pg_data:
