# Generated by Django 4.2.13 on 2024-07-13 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("flow_meter", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={"verbose_name": "Товар", "verbose_name_plural": "Товары"},
        ),
    ]
