# Generated by Django 4.2.13 on 2024-07-30 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("flow_meter", "0002_alter_product_category_alter_product_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                db_index=True, max_length=200, verbose_name="Категория"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="flow_meter.category",
                verbose_name="Категория",
            ),
        ),
    ]
