name: Django

on:
  - push

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
      - run: pip install --upgrade pip
      - run: pip install --editable .
      - run: cd app
      - run: python3 manage.py migrate
      - run: python3 manage.py test
